data_path: "data/add.csv"
test_size: 0.2
hidden_size: 40
learning_rate: 0.001
epochs: 5000
log_interval: 50
batch_size: 32
world_size: 0 # For distributed training, set this to the number of processes (e.g., GPUs)
rank: 0 # Rank of the current process
